["Physical Settings"]
L = [4, 4, 4, 4]
"Î²" = 5.7
kind_of_gaction = "wilson"
Ntherm = 10
Nsteps = 100
initial = "cold"
update_method = "Metropolis"
multi_hit = 5
metro_target_acc = 0.5

["System Settings"]               
logdir = "./logs/L4x4x4x4_beta5.7"
logfile = "Metro_test.txt"
measurement_basedir = "./measurements/L4x4x4x4_beta5.7"
measurement_dir = "Metro_test"
randomseeds = "[Xoshiro(1206)]"

["Measurement set".measurement_methods.Polyakov_loop]
measure_every = 5
methodname = "polyakov_loop"

["Measurement set".measurement_methods.Topological_charge]
measure_every = 5
kinds_of_topological_charge = ["plaquette", "clover", "improved"]
methodname = "topological_charge"

["Measurement set".measurement_methods.Plaquette]
measure_every = 5
methodname = "plaquette"